name: Download Roboto Mono fonts

on:
  workflow_dispatch:

jobs:
  downlaod_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Recreate noto fonts directory
        run: |
          rm -rf roboto_mono
          mkdir roboto_mono

      - name: Clone RobotoMono fonts repository
        run: |
          git clone --depth 1 https://github.com/googlefonts/RobotoMono.git

      - name: Copy license file and RobotoMono TTF fonts
        run: |
          cp RobotoMono/fonts/ttf/*.ttf roboto_mono/
          cp RobotoMono/LICENSE.txt roboto_mono/
          rm -rf RobotoMono

      - name: Check for changes
        id: git-check
        run: |
          git add roboto_mono
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "HAS_CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.HAS_CHANGES == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "chore: Update roboto mono fonts"
          git push

